before_script:
  - "mysql -e 'drop database if exists connect_mng_test; create database connect_mng_test;'"

env:
  - DB_HOST="127.0.0.1" DB_PORT=3306 DB_USER="root" DB_PASS="" DB_NAME="connect_mng_test"

language: node_js
node_js:
  - "6"
  - "4"

before_install: npm install -g grunt-cli
install: npm install