before_script:
  - "mysql -e 'drop database if exists connect_mng_test; create database connect_mng_test;'"

env:
  - DB_HOST="127.0.0.1" DB_PORT=3306 DB_USER="root" DB_PASS="" DB_NAME="connect_mng_test"

language: node_js
node_js:
  - "0.10"
  - "0.8"